service: dynamodb-to-elasticsearch

plugins:
  - serverless-python-requirements
  - serverless-hooks
provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  deploymentBucket: ${self:custom.deploymentBucketVariable.${self:provider.stage}}
  tags:
    EngTeam: Platform-Integration
    Environment: ${self:provider.stage}
    GitRepo: 'hearsaycorp/dynamodb-to-elasticsearch'
    ServiceName: ${self:service}
  environment:
    ENV: ${self:provider.stage}
    SENTRY_DSN: ${self:custom.sentry.dsn}
    SENTRY_ENVIRONMENT: ${opt:stage, self:provider.stage}

custom:
  aws_account:
    dev: 590762009186
    prod: 302137437361
  sentry:
    dsn: ${self:custom.sentry_dsns.${self:provider.stage}}
  sentry_dsns:
    dev: https://905bad4fc7e148cdb08ad3ab493093f0@o32711.ingest.sentry.io/76042
    prod: https://69f9daba4c7b49619c31c889047956eb@o32711.ingest.sentry.io/5954567
  deploymentBucketVariable:
    dev: hsl-dev-us-west-2-serverless
    staging: hsl-prod-us-west-2-serverless
    prod: hsl-prod-us-west-2-serverless
  subnet_ids:
    dev:
      - subnet-afd4f8e6
      - subnet-41392c26
      - subnet-71dc742a
    prod:
      - subnet-31a12b59
      - subnet-86e7f8ee
      - subnet-e095b5a6
  dev_sg:
    securityGroupIds:
      - sg-4b39f331
    subnetIds: ${self:custom.subnet_ids.dev}
  activities_sg:
    dev: ${self:custom.dev_sg}
    prod: 
      securityGroupIds:
        - sg-cfac19aa
      subnetIds: ${self:custom.subnet_ids.prod}

package:
  individually: true
  exclude:
    - node_modules/**
    - venv/**
  include:
    - "**"
    - index.py
    - settings.py

functions:
  authorize-request:
    name: ${self:service}-${self:provider.stage}
    description: authorize API request
    handler: index.lambda_handler
    memorySize: 4096
    timeout: 900
    vpc: ${self:custom.activities_sg.${self:provider.stage}}
    events:
      - stream:
          arn: arn:aws:dynamodb:us-west-2:590762009186:table/pnw-dev-helm-group-search/stream/2020-11-18T19:53:11.889
          batchsize: 100
          enabled: true
          startingPosition: TRIM_HORIZON
          parallelizationFactor: 1
          maximumRecordAgeInSeconds: 60
          bisectBatchOnFunctionError: false
