version: 2
workflows:
  version: 2
  continuous-delivery:
    jobs:
      - deploy-dev:
          context: aws-dev
          filters:
            branches:
              only:
                - main
      - lgtm:
          filters:
            branches:
              only:
                - main
          type: approval
          requires:
            - deploy-dev
      - deploy-prod:
          context: aws-prod
          filters:
            branches:
              only:
                - main
          requires:
            - lgtm
jobs:
  deploy-dev:
    docker:
      - image: circleci/python:3.8-node
    steps:
      - checkout
      - run:
          name: install serverless dependencies & set credentials
          command: |
            sudo npm install -g serverless
            npm install
            serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile hearsaydev
      - run:
          name: install pipenv
          command: |
           sudo pip3 install pipenv
           pipenv install
      - run:
          name: deploy to dev
          command: |
            sls deploy --stage dev
  deploy-prod:
    docker:
      - image: circleci/python:3.8-node
    steps:
      - checkout
      - run:
          name: install serverless dependencies & set credentials
          command: |
            sudo npm install -g serverless
            npm install
            serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile hearsayprod
      - run:
          name: install pipenv
          command: |
           sudo pip3 install pipenv
           pipenv install
      - run:
          name: deploy to prod
          command: |
            sls deploy --stage prod

